<?php declare(strict_types=1);

namespace Laswitchtech\CoreWeb\Router\Config\Http;

/**
 * Apache .htaccess configuration generator.
 *
 * Emits RewriteEngine rules that route all requests to index.php,
 * supporting both DocumentRoot and subdirectory deployments.
 *
 * Usage:
 *     echo \Laswitchtech\CoreWeb\Router\Config\Http\Apache::generate('/app');
 *
 * Documentation: docs/development/architecture/Router/Config/Http/Apache.md
 */
final class Apache
{
    /**
     * Generate an .htaccess snippet for Apache with mod_rewrite.
     *
     * @param string $subdir Subdirectory path relative to DocumentRoot (empty = root).
     *                       Pass '/app' for deployments at https://example.com/app/.
     * @return string Complete .htaccess content ready to write to disk or echo inline.
     */
    public static function generate(string $subdir = ''): string
    {
        // Normalise: strip leading/trailing slashes, keep empty -> root deployment.
        $trimmed = trim($subdir, '/');

        // RewriteBase is the URL prefix where the application lives.
        // For '' → '/', for 'app' → '/app/', for 'foo/bar/baz' → '/foo/bar/'.
        $rewriteBase = ($trimmed !== '') ? '/' . $trimmed . '/' : '/';

        if ($trimmed === '') {
            // ================================================================
            // ROOT deployment (DocumentRoot = app root) — simplest case.
            // Only intercepts requests that don't map to a real file/directory.
            // ================================================================
            return <<<HTACCESS
# Apache .htaccess — Core-Web Router (root deployment)
# Auto-generated by Laswitchtech\\CoreWeb\\Router\\Config\\Http\\Apache::generate()
# Do not edit manually; regenerate with `core.deploy apache` or via admin panel.

<IfModule mod_rewrite.c>
    RewriteEngine On



    # Skip requests that map to real files or directories.
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d

    # Route everything else to index.php.
    RewriteRule . index.php [L]
</IfModule>

# Block access to hidden files/dirs (.git, .env, etc.).
<IfModule mod_autoindex.c>
    Options -Indexes
</IfModule>

HTACCESS;
        }

        // ================================================================
        // SUBDIRECTORY deployment (e.g. https://example.com/app/).
        // RewriteBase tells Apache where the application root lives under DocumentRoot.
        // ================================================================
        return <<<HTACCESS
# Apache .htaccess — Core-Web Router (subdirectory deployment)
# For deployments at {$rewriteBase} your URL prefix is "{$trimmed}".
# Auto-generated by Laswitchtech\\CoreWeb\\Router\\Config\\Http\\Apache::generate()
# Do not edit manually; regenerate with `core.deploy apache` or via admin panel.

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase {$rewriteBase}



    # Only route when the request does NOT map to a real file/directory.
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d

    # Send remaining requests to the app's index.php (relative to RewriteBase).
    RewriteRule . index.php [L]
</IfModule>

# Block access to hidden files/dirs (.git, .env, etc.).
<IfModule mod_autoindex.c>
    Options -Indexes
</IfModule>

HTACCESS;
    }

    /**
     * Write the generated snippet to an .htaccess file on disk.
     *
     * Overwrites the existing file atomically (temp + rename).
     * Returns the path written or null on failure.
     */
    public static function writeToFile(string $path, string $subdir = ''): ?string
    {
        $content = self::generate($subdir);

        $tmpDir = dirname($path);

        // Ensure directory exists and is writable.
        if (!is_dir($tmpDir)) {
            return null;
        }

        $tmpFile = tempnam($tmpDir, '.htaccess_');

        if ($tmpFile === false || file_put_contents($tmpFile, $content) === false) {
            @unlink($tmpFile);
            return null;
        }

        // Atomic rename to overwrite existing .htaccess.
        if (!rename($tmpFile, $path)) {
            @unlink($tmpFile);
            return null;
        }

        return $path;
    }
}
