<?php declare(strict_types=1);

namespace Laswitchtech\CoreWeb\Router\Config\Http;

/**
 * PHP built-in web server router file generator.
 *
 * Emits a small `router.php` that returns `false` for static files
 * (letting PHP serve them directly) and forwards everything else to index.php.
 *
 * Usage:
 *     php -S localhost:8000 router.php
 */
final class Builtin
{
    /**
     * Generate a router.php file content for PHP's built-in web server.
     *
     * @param string $entry Front controller entry point (default 'index.php').
     * @return string Complete router.php file content ready to write to disk.
     */
    public static function generate(string $entry = 'index.php'): string
    {
        $entry = ltrim($entry, '/');

        return <<<ROUTER
<?php
// PHP built-in web server router — generated by Core-Web
// Usage: php -S localhost:8000 router.php

\$path   = parse_url(\$_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH);
\$file   = __DIR__ . \$path;

// Serve static files directly; everything else goes to the front controller.
if (\$path !== '/' && is_file(\$file)) {
    return false;
}

require __DIR__ . '/{$entry}';
ROUTER;
    }

    /**
     * Write the generated router file to disk.
     *
     * @return string|null The path written, or null on failure.
     */
    public static function writeToFile(string $path, string $entry = 'index.php'): ?string
    {
        $content   = self::generate($entry);
        $tmpDir    = dirname($path);

        if (!is_dir($tmpDir)) {
            return null;
        }

        $tmpFile = tempnam($tmpDir, 'builtin_');

        if ($tmpFile === false || file_put_contents($tmpFile, $content) === false) {
            @unlink($tmpFile);
            return null;
        }

        if (!rename($tmpFile, $path)) {
            @unlink($tmpFile);
            return null;
        }

        return $path;
    }
}
